services:
  ocr-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocr-mvp-streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./outputs:/app/outputs
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
